// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Registration.Models;

public partial class Promocode
{
    [Key]
    public int Id { get; set; }

    [Column("Promocode")]
    [StringLength(5)]
    public string Promocode1 { get; set; }
}