// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Registration.Models;

public partial class User
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Please, use letters in the first name. Digits are not allowed.")]
    public string FirstName { get; set; }

    [StringLength(50)]
    [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Please, use letters in the first name. Digits are not allowed.")]
    public string LastName { get; set; }
    [Range(12, 120)]
    public byte? Age { get; set; }

    [StringLength(50)]
    public string UserName { get; set; }

    [StringLength(255)]
    [EmailAddress(ErrorMessage ="Incorrect Email")]
    public string Email { get; set; }

    [StringLength(13, ErrorMessage="Password Lenght Should Be between 6 and 13",MinimumLength = 6)]
    public string Password { get; set; }

    [StringLength(13)]
    [Compare("Password",ErrorMessage ="Password Doesnt Match")]
    public string PasswordCheck { get; set; }

    [StringLength(20)]
    [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{3})$", ErrorMessage = "Please, use numbers in the phone number. Letters are not allowed.")]
    public string PhoneNumber { get; set; }

    [StringLength(5)]
    public string Promocode { get; set; }

    public int? RoleId { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("Users")]
    public virtual Role Role { get; set; }
}