// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Registration.Models;

public partial class User
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; }

    [StringLength(50)]
    public string LastName { get; set; }

    public byte? Age { get; set; }

    [StringLength(50)]
    public string UserName { get; set; }

    [StringLength(255)]
    [EmailAddress(ErrorMessage ="Incorrect Email")]
    public string Email { get; set; }

    //[Range(6,13,ErrorMessage ="Password Should Be In Range Of 6 And 13")]
    [StringLength(13)]
    public string Password { get; set; }

    //[Range(6, 13, ErrorMessage = "Password Should Be In Range Of 6 And 13")]
    [StringLength(13)]
    public string PasswordCheck { get; set; }

    [StringLength(20)]
    public string PhoneNumber { get; set; }

    [StringLength(5)]
    public string Promocode { get; set; }

    public int? RoleId { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("Users")]
    public virtual Role Role { get; set; }
}